
print("##           ")
print("##   ########")  
print("##   ##    ##")
print("##   ##    ##")
print("##   ##    ##")
print("##   ##    ##")
print("##         ##")
print("##         ##")
print("#######    ##")
print("           ##")
print("JOGO DE ADIVINHAÇÃO")
